only: pulls

pulls:
  daysUntilStale: 13
  daysUntilClose: 1
  onlyLabels:
    - 'needs work'
  exemptLabels:
    - discussion
  staleLabel: stale
  exemptAssignees: true
  markComment: >
    This pull request will be closed tomorrow because it has not had recent
    activity after being reviewed. If you are still interested in adding your
    project to the site, please submit a new pull request and address the above
    feedback. Thank you for your contribution!
  closeComment: false
  unmarkComment: false
