pulls:
  daysUntilStale: 14
  daysUntilClose: 0
  onlyLabels:
    - 'needs work'
  exemptLabels:
    - discussion
  staleLabel: stale
  exemptAssignees: true
  markComment: >
    This pull request will be closed because it has not had recent activity after
    being reviewed. If you are still interested in adding your project to the site,
    please submit a new pull request and address the above feedback. Thank you
    for your contribution!
