AllCops:
  NewCops: enable
  Include:
    - '.github/actions/**/*.rb'
    - 'scripts/**/*.rb'

Layout/LineLength:
  Max: 186

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Metrics/AbcSize:
  Max: 66

Metrics/MethodLength:
  Max: 59
