sudo: false

notifications:
  email: false

services:
  - docker

script:
  - docker build .

branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
