title: up-for-grabs.net

exclude:
  - CNAME
  - Gemfile*
  - tests
  - README.md
  - scripts
  - .travis.yml
  - vendor
  - node_modules
  - package.json
  - yarn.lock
  - .eslintrc.json
  - .prettierrc.json
  - docs

github: [metadata]

