title: up-for-grabs.net

exclude:
  - .github
  - assets
  - docs
  - licenses
  - node_modules
  - scripts
  - tests
  - .editorconfig
  - .eslintrc.json
  - .prettierrc.json
  - .rubocop.yml
  - .ruby-version
  - CNAME
  - Dockerfile
  - docker-compose.yml
  - Gemfile*
  - jest.config.js
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - tsconfig.json

github: [metadata]

